spring:
  application:
    name: ASCII-TON
  profiles:
    include: api

  # H2 데이터베이스 설정 (테스트용 DB)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # 웹에서 DB를 직접 볼 수 있게 설정

  jpa:
    defer-datasource-initialization:
      true
    hibernate:
      ddl-auto: update # 엔티티 수정 시 DB 테이블 자동 업데이트
    show-sql: true # 실행되는 SQL문을 로그로 보여줌

# 우리가 직접 사용할 커스텀 설정
google:
  genai:
    model: "models/gemini-flash-latest"

# Swagger(SpringDoc) 설정
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html # 문서 접속 주소
    groups-order: asc
    operations-sorter: alpha
